sudo -v;
uname -a;
journalctl -xe;
/etc/init.d/httpd status verbose;
/etc/init.d/webmin status verbose;
/etc/init.d/avahi-daemon status verbose;
/etc/init.d/bind9 status verbose;
/etc/init.d/cron status verbose;
/etc/init.d/dovecot status verbose;
/etc/init.d/fail2ban status verbose;
/etc/init.d/mysql status verbose;
/etc/init.d/nginx status verbose;
/etc/init.d/php7.1-fpm status verbose;
/etc/init.d/postfix status verbose;
/etc/init.d/procps status verbose;
/etc/init.d/rsync status verbose;
/etc/init.d/rsyslog status verbose;
/etc/init.d/saslauthd status verbose;
/etc/init.d/squid status verbose;
/etc/init.d/ssh status verbose;
/etc/init.d/udev status verbose;
/etc/init.d/usermin status verbose;
/etc/init.d/webmin status verbose;
/etc/init.d/x11-common status verbose;
